// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9JMz-RM3vPFMxgVghzRDc7N2_0AaKX-w',
    appId: '1:314063637507:web:938c1a09e81b7340e4d236',
    messagingSenderId: '314063637507',
    projectId: 'eplanetofficiel',
    authDomain: 'eplanetofficiel.firebaseapp.com',
    storageBucket: 'eplanetofficiel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuw-3bm0LBE7Ifx7pYU7soEODd-aHhzaw',
    appId: '1:314063637507:android:60960275ed85aeb0e4d236',
    messagingSenderId: '314063637507',
    projectId: 'eplanetofficiel',
    storageBucket: 'eplanetofficiel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjgVzHVBntxN00_9CXK-2dFOLt15vqfSQ',
    appId: '1:314063637507:ios:0c0423c53ccc7a3fe4d236',
    messagingSenderId: '314063637507',
    projectId: 'eplanetofficiel',
    storageBucket: 'eplanetofficiel.appspot.com',
    iosClientId: '314063637507-9aheg8ddgasn0s0at11sjg9btllj871k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePlanetOfficiel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjgVzHVBntxN00_9CXK-2dFOLt15vqfSQ',
    appId: '1:314063637507:ios:00e3a0d80666a6fde4d236',
    messagingSenderId: '314063637507',
    projectId: 'eplanetofficiel',
    storageBucket: 'eplanetofficiel.appspot.com',
    iosClientId: '314063637507-psj6f49qb3uvqici73d9l0l2bfil0c9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePlanetOfficiel.RunnerTests',
  );
}
